#include "PluginSDK.h"
#include "D3D9.h"
#include <map>

class IPlugin
{
public:
	IPlugin(char* author, char* name, int version);
	~IPlugin();

	static char* GetAuthor();
	static char* GetName();
	static int GetVersion();
	static void AddMenu(std::string name, std::string title);
	static void AddMenu(std::string name, std::string title, std::string parentName);
	static void AddCheckBox(std::string menu, std::string name, std::string title, bool value);
	static void AddCheckBox(std::string name, std::string title, bool value);
	static void AddToggle(std::string menu, std::string name, std::string title, bool value, int defaultKey);
	static void AddToggle(std::string name, std::string title, bool value, int defaultKey);
	static void AddColor(std::string menu, std::string name, std::string title, DWORD value);
	static void AddColor(std::string menu, std::string name, std::string title, float R, float G, float B, float A);
	static void AddColor(std::string name, std::string title, DWORD value);
	static void AddColor(std::string name, std::string title, float R, float G, float B, float A);
	static void AddFloat(std::string menu, std::string name, std::string title, float minValue, float maxValue, float value);
	static void AddFloat(std::string name, std::string title, float minValue, float maxValue, float value);
	static void AddInteger(std::string menu, std::string name, std::string title, int minValue, int maxValue, int value);
	static void AddInteger(std::string name, std::string title, int minValue, int maxValue, int value);
	static void AddKey(std::string menu, std::string name, std::string title, int defaultKey);
	static void AddKey(std::string name, std::string title, int defaultKey);
	static void AddSelection(std::string menu, std::string name, std::string title, int defaultIdx, std::vector<std::string> const& names);
	static void AddSelection(std::string name, std::string title, int defaultIdx, std::vector<std::string> const& names);
	static void UpdateInteger(std::string menu, std::string name, int value);
	static void UpdateInteger(std::string name, int value);
	static IMenu* GetMenu(std::string name);
	static IMenu* GetMenu();
	static bool MenuExists(std::string name);
	static bool MenuOptionExists(std::string menu, std::string name);
	static IMenuOption* GetMenuOption(std::string menu, std::string name);
	static IMenuOption* GetMenuOption(std::string name);
	static bool GetMenuBoolean(std::string menu, std::string name);
	static bool GetMenuBoolean(std::string name);
	static Vec4 GetMenuColor(std::string menu, std::string name);
	static Vec4 GetMenuColor(std::string name);
	static float GetMenuFloat(std::string menu, std::string name);
	static float GetMenuFloat(std::string name);
	static int GetMenuInteger(std::string menu, std::string name);
	static int GetMenuInteger(std::string name);

	static void RegisterOrbwalkBeforeAttackEvent(std::function<void(IUnit*)> function);
	static void RegisterOrbwalkOnAttackEvent(std::function<void(IUnit*, IUnit*)> function);
	static void RegisterOrbwalkAfterAttackEvent(std::function<void(IUnit*, IUnit*)> function);
	static void RegisterOrbwalkTargetChangeEvent(std::function<void(IUnit*, IUnit*)> function);
	static void RegisterOrbwalkNonKillableMinionEvent(std::function<void(IUnit*)> function);
	static void RegisterGameUpdateEvent(std::function<void()> function);
	static void RegisterRenderEvent(std::function<void()> function);
	static void RegisterSpellCastEvent(std::function<void(CastedSpell const&)> function);
	static void RegisterUnitDeathEvent(std::function<void(IUnit*)> function);
	static void RegisterCreateObjectEvent(std::function<void(IUnit*)> function);
	static void RegisterDestroyObjectEvent(std::function<void(IUnit*)> function);
	static void RegisterDoCastEvent(std::function<void(CastedSpell const&)> function);
	static void RegisterInterruptibleEvent(std::function<void(InterruptibleSpell const&)> function);
	static void RegisterGapCloserEvent(std::function<void(GapCloserSpell const&)> function);
	static void RegisterIssueOrderEvent(std::function<bool(IUnit*, eGameObjectOrder, Vec3*, IUnit*)> function);
	static void RegisterBuffAddEvent(std::function<void(IUnit*, void*)> function);
	static void RegisterBuffRemoveEvent(std::function<void(IUnit*, void*)> function);
	static void RegisterGameEndEvent(std::function<void()> function);
	static void RegisterLevelUpEvent(std::function<void(IUnit*, int)> function);
	static void RegisterPreCastEvent(std::function<bool(eSpellSlot, IUnit*, Vec3*, Vec3*)> function);
	static void RegisterOrbwalkFindTargetEvent(std::function<IUnit*()> function);
	static void RegisterDashEvent(std::function<void(UnitDash*)> function);
	static void RegisterD3DPresentEvent(std::function<void(IDirect3DDevice9*)> function);
	static void RegisterD3DPreResetEvent(std::function<void(IDirect3DDevice9*)> function);
	static void RegisterD3DPostResetEvent(std::function<void(IDirect3DDevice9*)> function);
	static void RegisterRenderBehindHudEvent(std::function<void()> function);
	static void RegisterWndProcEvent(std::function<bool(HWND, UINT, WPARAM, LPARAM)> function);
	static void RegisterEnterVisibleEvent(std::function<void(IUnit*)> function);
	static void RegisterExitVisibleEvent(std::function<void(IUnit*)> function);
	static void RegisterUpdateChargedSpellEvent(std::function<void(eSpellSlot, Vec3*, bool*, bool*)> function);
	static void RegisterPlayAnimationEvent(std::function<void(IUnit*, std::string const)> function);
	static void RegisterPauseAnimationEvent(std::function<void(IUnit*)> function);
	static void RegisterJungleNotificationEvent(std::function<void(JungleNotifyData*)> function);
	static void RegisterNewPathEvent(std::function<void(IUnit*, std::vector<Vec3> const&)> function);
	static void RegisterTeleportEvent(std::function<void(OnTeleportArgs* args)> function);

private:
	static char* Author;
	static char* Name;
	static int Version;
	static std::map<std::string, IMenu*> Menus;
	static std::map<std::string, std::map<std::string, IMenuOption*>> MenuOptions;

	static std::vector<std::function<void(IUnit*)>> OrbwalkBeforeAttackEvents;
	static std::vector<std::function<void(IUnit*, IUnit*)>> OrbwalkOnAttackEvents;
	static std::vector<std::function<void(IUnit*, IUnit*)>> OrbwalkAfterAttackEvents;
	static std::vector<std::function<void(IUnit*, IUnit*)>> OrbwalkTargetChangeEvents;
	static std::vector<std::function<void(IUnit*)>> OrbwalkNonKillableMinionEvents;
	static std::vector<std::function<void()>> GameUpdateEvents;
	static std::vector<std::function<void()>> RenderEvents;
	static std::vector<std::function<void(CastedSpell const&)>> SpellCastEvents;
	static std::vector<std::function<void(IUnit*)>> UnitDeathEvents;
	static std::vector<std::function<void(IUnit*)>> CreateObjectEvents;
	static std::vector<std::function<void(IUnit*)>> DestroyObjectEvents;
	static std::vector<std::function<void(CastedSpell const&)>> DoCastEvents;
	static std::vector<std::function<void(InterruptibleSpell const&)>> InterruptibleEvents;
	static std::vector<std::function<void(GapCloserSpell const&)>> GapCloserEvents;
	static std::vector<std::function<bool(IUnit*, eGameObjectOrder, Vec3*, IUnit*)>> IssueOrderEvents;
	static std::vector<std::function<void(IUnit*, void*)>> BuffAddEvents;
	static std::vector<std::function<void(IUnit*, void*)>> BuffRemoveEvents;
	static std::vector<std::function<void()>> GameEndEvents;
	static std::vector<std::function<void(IUnit*, int)>> LevelUpEvents;
	static std::vector<std::function<bool(eSpellSlot, IUnit*, Vec3*, Vec3*)>> PreCastEvents;
	static std::vector<std::function<IUnit*()>> OrbwalkFindTargetEvents;
	static std::vector<std::function<void(UnitDash*)>> DashEvents;
	static std::vector<std::function<void(IDirect3DDevice9*)>> D3DPresentEvents;
	static std::vector<std::function<void(IDirect3DDevice9*)>> D3DPreResetEvents;
	static std::vector<std::function<void(IDirect3DDevice9*)>> D3DPostResetEvents;
	static std::vector<std::function<void()>> RenderBehindHudEvents;
	static std::vector<std::function<bool(HWND, UINT, WPARAM, LPARAM)>> WndProcEvents;
	static std::vector<std::function<void(IUnit*)>> EnterVisibleEvents;
	static std::vector<std::function<void(IUnit*)>> ExitVisibleEvents;
	static std::vector<std::function<void(eSpellSlot, Vec3*, bool*, bool*)>> UpdateChargedSpellEvents;
	static std::vector<std::function<void(IUnit*, std::string const)>> PlayAnimationEvents;
	static std::vector<std::function<void(IUnit*)>> PauseAnimationEvents;
	static std::vector<std::function<void(JungleNotifyData*)>> JungleNotificationEvents;
	static std::vector<std::function<void(IUnit*, std::vector<Vec3> const&)>> NewPathEvents;
	static std::vector<std::function<void(OnTeleportArgs* args)>> TeleportEvents;

	static bool OrbwalkBeforeAttackEventHandlerAdded;
	static bool OrbwalkOnAttackEventHandlerAdded;
	static bool OrbwalkAfterAttackEventHandlerAdded;
	static bool OrbwalkTargetChangeEventHandlerAdded;
	static bool OrbwalkNonKillableMinionEventHandlerAdded;
	static bool GameUpdateEventHandlerAdded;
	static bool RenderEventHandlerAdded;
	static bool SpellCastEventHandlerAdded;
	static bool UnitDeathEventHandlerAdded;
	static bool CreateObjectEventHandlerAdded;
	static bool DestroyObjectEventHandlerAdded;
	static bool DoCastEventHandlerAdded;
	static bool InterruptibleEventHandlerAdded;
	static bool GapCloserEventHandlerAdded;
	static bool IssueOrderEventHandlerAdded;
	static bool BuffAddEventHandlerAdded;
	static bool BuffRemoveEventHandlerAdded;
	static bool GameEndEventHandlerAdded;
	static bool LevelUpEventHandlerAdded;
	static bool PreCastEventHandlerAdded;
	static bool OrbwalkFindTargetEventHandlerAdded;
	static bool DashEventHandlerAdded;
	static bool D3DPresentEventHandlerAdded;
	static bool D3DPreResetEventHandlerAdded;
	static bool D3DPostResetEventHandlerAdded;
	static bool RenderBehindHudEventHandlerAdded;
	static bool WndProcEventHandlerAdded;
	static bool EnterVisibleEventHandlerAdded;
	static bool ExitVisibleEventHandlerAdded;
	static bool UpdateChargedSpellEventHandlerAdded;
	static bool PlayAnimationEventHandlerAdded;
	static bool PauseAnimationEventHandlerAdded;
	static bool JungleNotificationEventHandlerAdded;
	static bool NewPathEventHandlerAdded;
	static bool TeleportEventHandlerAdded;

	PLUGIN_EVENT(void) OnOrbwalkBeforeAttack(IUnit* target);
	PLUGIN_EVENT(void) OnOrbwalkOnAttack(IUnit* source, IUnit* target);
	PLUGIN_EVENT(void) OnOrbwalkAfterAttack(IUnit* source, IUnit* target);
	PLUGIN_EVENT(void) OnOrbwalkTargetChange(IUnit* oldTarget, IUnit* newTarget);
	PLUGIN_EVENT(void) OnOrbwalkNonKillableMinion(IUnit* minion);
	PLUGIN_EVENT(void) OnGameUpdate();
	PLUGIN_EVENT(void) OnRender();
	PLUGIN_EVENT(void) OnSpellCast(CastedSpell const& spell);
	PLUGIN_EVENT(void) OnUnitDeath(IUnit* source);
	PLUGIN_EVENT(void) OnCreateObject(IUnit* source);
	PLUGIN_EVENT(void) OnDestroyObject(IUnit* source);
	PLUGIN_EVENT(void) OnDoCast(CastedSpell const& spell);
	PLUGIN_EVENT(void) OnInterruptible(InterruptibleSpell const& spell);
	PLUGIN_EVENT(void) OnGapCloser(GapCloserSpell const& spell);
	PLUGIN_EVENT(bool) OnIssueOrder(IUnit* source, eGameObjectOrder orderIdx, Vec3* position, IUnit* target);
	PLUGIN_EVENT(void) OnBuffAdd(IUnit* source, void* buffData);
	PLUGIN_EVENT(void) OnBuffRemove(IUnit* source, void* buffData);
	PLUGIN_EVENT(void) OnGameEnd();
	PLUGIN_EVENT(void) OnLevelUp(IUnit* source, int newLevel);
	PLUGIN_EVENT(bool) OnPreCast(eSpellSlot slot, IUnit* target, Vec3* startPosition, Vec3* endPosition);
	PLUGIN_EVENT(IUnit*) OnOrbwalkFindTarget();
	PLUGIN_EVENT(void) OnDash(UnitDash* dash);
	PLUGIN_EVENT(void) OnD3DPresent(IDirect3DDevice9* device);
	PLUGIN_EVENT(void) OnD3DPreReset(IDirect3DDevice9* device);
	PLUGIN_EVENT(void) OnD3DPostReset(IDirect3DDevice9* device);
	PLUGIN_EVENT(void) OnRenderBehindHud();
	PLUGIN_EVENT(bool) OnWndProc(HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam);
	PLUGIN_EVENT(void) OnEnterVisible(IUnit* source);
	PLUGIN_EVENT(void) OnExitVisible(IUnit* source);
	PLUGIN_EVENT(void) OnUpdateChargedSpell(eSpellSlot slot, Vec3* position, bool* releaseCast, bool* triggerEvent);
	PLUGIN_EVENT(void) OnPlayAnimation(IUnit* source, std::string const animation);
	PLUGIN_EVENT(void) OnPauseAnimation(IUnit* source);
	PLUGIN_EVENT(void) OnJungleNotification(JungleNotifyData* data);
	PLUGIN_EVENT(void) OnNewPath(IUnit* source, std::vector<Vec3> const& path);
	PLUGIN_EVENT(void) OnTeleport(OnTeleportArgs* args);
};

extern IPlugin* GPlugin;
